// product
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// product_uses_material
export const FETCH_PRODUCT_USE_MATERIAL = 'FETCH_PRODUCT_USE_MATERIAL';
export const PRODUCT_USE_MATERIAL = 'PRODUCT_USE_MATERIAL';
export const PRODUCT_UNUSE_MATERIAL = 'PRODUCT_UNUSE_MATERIAL';
