export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP';
export const RESEND_CODE = 'RESEND_CODE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_AND_SUBMIT = 'FORGOT_PASSWORD_AND_SUBMIT';
