# This is a basic workflow to help you get started with Actions

name: Deploy to Chalice

on:
  push:
    branches:
      - master
    paths:
      - 'server/*'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: chalice deploy
      uses: jayef0/chalice-extended-action@v0.1.0
      env:
        WORKING_DIRECTORY: server
        REQUIREMENTS_FILE: requirements.txt
        OPERATION: deploy
        STAGE: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
