name: Deploy fetchMaterials
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: zip
        run: |
          cd server
          mkdir build
          zip -r -j ./build/fetchMaterials.zip fetchMaterials/lambda_function.py
      - name: deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: fetchMaterials
          zip_file: server/build/fetchMaterials.zip
          runtime: python3.8
