name: Deploy Lambda Functions
on: [push]
jobs:
  deploy_source:
    name: Fetch Materials
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: |
          cd server
          npm ci
          npm run build
        env:
          CI: true
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: fetchMaterials
          zip_file: ./build/fetchMaterials.zip
