name: Deploy fetchMaterials
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        function-name: [fetchMaterials]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd server
          pip install -r requirements.txt -t ./${{ matrix.function-name }}
      - name: zip
        run: |
          cd server
          mkdir build
          cd ${{ matrix.function-name }}
          zip -r ./../build/${{ matrix.function-name }}.zip .
      - name: deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: ${{ matrix.function-name }}
          zip_file: server/build/${{ matrix.function-name }}.zip
          runtime: python3.8
